wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.9
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693957847.195632
    t:
      1:
      - 55
      - 86
      - 95
      - 105
      2:
      - 55
      - 86
      - 95
      - 105
      3:
      - 23
      4: 3.11.3
      5: 0.15.9
      8:
      - 1
      - 5
      9:
        2: langchain
